Adding other country maps
CaseyHillers/cartograms4all pull request #18
Opened 2017-07-22 10:49 UTC by larocque492

Other maps are working at last! 

The changes in index.js and functions.js add a lot to the practical use of the site. There's map selection now, support for a world projection and arbitrary latitude/longitude, and a few deleted functions that weren't being used anyway.

If there's a better way to do the menus feel free to tell me - I just took this menu straight off the Materialize website. It's wobbly but it will select different maps, at least upon refreshing the page. The only change I made to what was already there was making the existing dropdown the same orangey yellow as the one I added - this kind of seems in line with material design.

I also need to figure out how to refresh the data selection menu, as the rows do select new data just fine, but they still just show the old contents of other csv files. Thoughts/ideas?

2017-07-22 20:30 UTC, CaseyHillers commented
Tested the functionality out, it works as expected.

2017-07-22 20:40 UTC, CaseyHillers requested changes
Don't worry about the indentation, i'll run it through my Google JS guide formatter before we pull request it. Just do the other things I mentioned. Enum for map type will probably take the longest.

2017-07-22 20:40 UTC, CaseyHillers commented on app/index.html
> +    <!--div-- class="row">
Delete unused comments, help keeps the code clean

2017-07-22 20:40 UTC, CaseyHillers commented on app/index.html
> +              <li><a href="#" onclick="chooseCountry(0)">USA(default) </a></li>
Removed (default), best choice would be to have the currently selected one a different shade, but because of time we can just leave it as is

2017-07-22 20:40 UTC, CaseyHillers commented on app/index.html
> +              <!--select class="browser-default" id="field"></select-->
remove unused comments

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/cartogram.js
> +      console.log(topology, "hi")
we're removing console.logs from the code, so remove this one

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/functions.js
> + *
This should be in a doc and not in the code

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/functions.js
> +  console.log(" col is"+ col);
remove these console.logs

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/functions.js
> -  console.log("desiredYear: " + desiredYear);
remvoe these console logs

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/functions.js
> +     year = field.years[0];
make sure these are indented

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/functions.js
> +console.log("Initial map setup!");
remove the console log

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/index.js
> -var scale = .94;
keep scale, its used in zoom

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/index.js
> +* The default integer, 0, tells the map to take in data for and display the USA,
This should be an enum, and not a magic number

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/index.js
> -    .scale(scale)
leave this scale code in, its for zoom

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/index.js
> +    proj = d3.geo.conicConformal()
Why is the map being switched to conicConformal for its projection method?

2017-07-22 20:40 UTC, CaseyHillers commented on app/js/index.js
> +  console.log("calling parseHash(fieldsById)")
remove console log

2017-07-23 03:59 UTC, larocque492 commented on app/js/index.js
> +* The default integer, 0, tells the map to take in data for and display the USA,
Changed to check for strings, not numbers

2017-07-23 05:28 UTC, CaseyHillers requested changes
Hey it doesn't work when I switch the datatype to another region. I have to refresh the page and work from start. Is there anyway to fix this?


[10:26] 
`Uncaught TypeError: Cannot read property 'NAME' of undefined
   at SVGPathElement.<anonymous> (index.js:125)
   at SVGPathElement.o (d3.v3.min.js:1)
   at d3.v3.min.js:3
   at Y (d3.v3.min.js:1)
   at Array.Co.each (d3.v3.min.js:3)
   at Array.Co.attr (d3.v3.min.js:3)
   at index.js:124
   at d3.v3.min.js:1
   at Object.<anonymous> (d3.v3.min.js:1)
   at Object.t (d3.v3.min.js:1)`


[10:27] 
It just seems like the code needs to do a reset() whenever a new csv file is uploaded.


[10:27] 
That has to be fixed because the default feature autoloads the us census data with the us, so it won't work with the master

2017-07-23 05:28 UTC, CaseyHillers commented on app/js/index.js
> +* The default integer, 0, tells the map to take in data for and display the USA,
this is a good move, just saw it's a bit messy to do enums since they aren't native in JS

2017-07-25 02:19 UTC, CaseyHillers commented
Another branch was made to deal with just the merging process. This was a code review branch. Now that it's in master, we don't need it open any longer.

2017-07-25 02:19 UTC, closed without merging