Save/Load Backend+Frontend integration
CaseyHillers/cartograms4all pull request #21
Opened 2017-07-22 23:10 UTC by BrightSun95

User's can copy their own session ID from the sharing tab.
User's can save CSV's to the server; the CSV's are associated with their session ID.
Still working on/deciding how to load those server-side CSV's onto the client machine.
     a) serverside PHP could make copies of the other user's CSV and name the new copy based on 
         currrent user's session ID (this allows current user to have a copy of the other user's CSV 
         associated with their own session ID)
     b) might just give client a path to the other user's CSV. This is sufficient for temporary use but
         persist across sessions. (can't save it or load it)

2017-07-22 23:25 UTC, CaseyHillers requested changes
Uncaught TypeError: Cannot read property 'name' of undefined
    at saveCSV (functions.js:71)
    at saveSession (ui.js:65)
    at HTMLAnchorElement.onclick (index.html:98)

2017-07-22 23:25 UTC, CaseyHillers commented on app/css/style.css
>        width: 100%;
remove style.css from this

2017-07-22 23:25 UTC, CaseyHillers commented on app/js/functions.js
> -  zoom = d3.behavior.zoom()
put this back

2017-07-22 23:25 UTC, CaseyHillers commented on app/uploader/upload-manager.php
> +
why all the empty space at the end

2017-07-23 06:05 UTC, BrightSun95 commented on app/css/style.css
>        width: 100%;
Should I delete the whole CSS folder?

2017-07-23 07:28 UTC, BrightSun95 commented on app/js/functions.js
> -  zoom = d3.behavior.zoom()
Not sure why this looks like this in the pull request but it the stuff is back in if you check the branch source.

2017-07-23 22:01 UTC, CaseyHillers commented
This got moved to pull request #26

2017-07-23 22:01 UTC, closed without merging