Backend isolation
CaseyHillers/cartograms4all pull request #23
Opened 2017-07-23 04:11 UTC by klin10

Migration to isolated the server backend php script from our javascript front end libraries.

2017-07-23 05:52 UTC, CaseyHillers approved these changes
Looks good, i'll make the merge

2017-07-23 05:52 UTC, CaseyHillers commented on app/js/functions.js
> +var USER_DIRECTORY = "../../server/uploader/upload/";
This can be switched to /server/uploader/upload/ as that will point to the root of the project instead.

2017-07-23 06:12 UTC, CaseyHillers commented
Just waiting on Luke's PR to go through so nothing gets messed up there from this.

2017-07-25 21:50 UTC, CaseyHillers requested changes
make php files have same file name format

2017-07-25 21:50 UTC, CaseyHillers commented on app/js/index.js
> +var PHP_DIRECTORY = "../server/php/";
forward slash

2017-07-25 21:50 UTC, CaseyHillers commented on app/js/functions.js
> -
we should probably keep this line

2017-07-25 21:50 UTC, CaseyHillers commented on server/uploader/upload/BLANK
> +BLANK FILE
what's this for

2017-07-25 23:31 UTC, klin10 commented on server/uploader/upload/BLANK
> +BLANK FILE
BLANK FILE

2017-07-26 00:19 UTC, CaseyHillers approved these changes
Looks good, just update of what files need to be moved!

2017-07-26 00:19 UTC, merged