Luke upload csv
CaseyHillers/cartograms4all pull request #4
Opened 2017-07-09 23:52 UTC by BrightSun95

Added .gitignore
Users can 'upload' their own .csv for visualization.

2017-07-10 05:46 UTC, CaseyHillers requested changes
This all looks really good, let's just try out making those small changes to give this review system a test :+1:

2017-07-10 05:46 UTC, CaseyHillers commented on app/.gitignore
> +.DS_store
This shouldn't be needed since it's in the root

Here's a stack overflow I found that explains it more in depth: https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

2017-07-10 05:46 UTC, CaseyHillers commented on app/js/functions.js
> +  CSV_URL = URL.createObjectURL(USER_CSV); // create URL representing USER_CSV
This is a clever trick :)

2017-07-10 05:46 UTC, CaseyHillers commented on app/js/index.js
> +    console.log("Please upload a file");
Should change to something like
"Cartograms 4 All: Waiting for user inputted file"

2017-07-10 06:08 UTC, BrightSun95 commented on app/js/index.js
> +    console.log("Please upload a file");
oh yeah my bad, that was really just for debugging, there should probably be some HTML to tell the user they need to upload the file.

2017-07-11 03:28 UTC, CaseyHillers approved these changes

2017-07-11 03:40 UTC, merged